### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by thewilsonator** [BindBC/bindbc-loader#1]
Under Configuration:

Binding implementors typically will provide four configuration options: two for static bindings (`nobc` and `yesbc` versions) and two for dynamic bindings (`nogc` and `yesbc` versions).

should be 

(`nobc` and `yesbc` versions).

**Comment by chriscamacho** [comment]
did you mean (nogc and yesgc) ?

**Comment by drug007** [comment]
@mdparker , could you clarify this moment, please? It is really confusing.

**Comment by drug007** [comment]
Ah, now I see clearly that `nobc` was meant because `nogc` is used by default all over the place.

**Comment by mdparker** [comment]
Thanks for bumping this @drug007. I'd never noticed it. Sorry @thewilsonator!
