### ISSUE TITLE
"Expose" request

### ISSUE THREAD

**Issue by ParchmentWolf** [BindBC/bindbc-loader#7]
I am using this loader's "SharedLibrary" system to successfully load Mupen64Plus in D and find using it very convenient.

Unfortunately with 1 particular Quirk required out of Mupen64Plus I have to pass the _handle to the mupen64plus 'plugins' for the whole system to work... I had pulled the source and modify the private keyword off of the SharedLibrary structs _handle variable in order to properly pass that data to the plugins.

The request is that a native method to access that handle be added for official support in projects that would need access for cases like mine in the future.

I personally intend to use this (probably really often) for future projects and would prefer to point to the repo to use it rather than cloning a module that may be deprecated or outdated some time in the future.

**Comment by mdparker** [comment]
I don't like the idea of exposing the `SharedLibrary` handle directly. That would make it possible for the caller to close the library while the program thinks it's still open.

And in your case, you should be able to use `osal_dynlib_open`. It should be calling the same system APIs the bindbc loader calls (`LoadLibrary` and `dlopen`). Those functions are smart enough to recognize if a library has already been loaded into the process and will simply return another handle to it. When multiple handles are taken like that, the library will remain valid in the process until all of the handles have been closed.

So I don't see a good enough reason here to expose the raw handle from bindbc.
