### ISSUE TITLE
Compilation error on Windows 10

### ISSUE THREAD

**Issue by jordan4ibanez** [BindBC/bindbc-loader#9]
I just accidentally upgraded bindbc-loader and with DMD and LDC2 I get this error (windows 10):
```
C:\Users\Jordan\AppData\Local\dub\packages\bindbc-glfw-1.0.1\bindbc-glfw\source\bindbc\glfw\binddynamic.d(557,11): Deprecation: variable `bindbc.loader.system.bindWindows` is deprecated
C:\D\dmd2\windows\bin64\..\..\src\phobos\std\internal\windows\advapi32.d(36,9): Error: undefined identifier `HMODULE`, did you mean alias `HMODULE`?
```

**Comment by ichordev** [comment]
The first one is a deprecation warning, not an error. I recommend replacing that `bindWindows` check with a `version(Windows)` statement. If it's in a larger if-statement (e.g. `if(bindWindows && someBoolean)`) then you can replace it with this:
```d
(){ version(Windows) return true; else return false; }()
```
(this is what `bindWindows` looks like right now anyway)
If you *absolutely must* use BindBC-Loader to do version checks (which is a bit silly, hence why those symbols are now deprecated) then specify the `bindbc-loader` version to be `=1.0.1` in your dub config file and run `dub upgrade`.

As for the `HMODULE` thing, I suspect that's a domino-effect error? If it doesn't go away, you might have to look at Phobos' Windows API bindings.

**Comment by ichordev** [comment]
Ah I see now that this issue was actually coming from BindBC-glfw. Either way, if you update BindBC-glfw it should be fixed.
You can use `-d` to ignore deprecation warnings until they’re resolved if you encounter any more. However, if they _do_ come from your code, then obviously I wouldn’t recommend ignoring them.
